[tool.poetry]
name = "fareview"
version = "1.0.0"
description = "A simple, fast market price scanner."
authors = ["Jerry Ng <ngshiheng@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Scrapy = "^2.5.0"
scrapy-fake-useragent = "^1.4.4"
ipython = "^7.25.0"
sentry-sdk = "^1.3.1"
psycopg2-binary = "^2.9.1"
SQLAlchemy = "^1.4.22"
price-parser = "^0.3.4"
colorlog = "^5.0.1"
python-telegram-bot = "^13.7"
SQLAlchemy-Utils = "^0.37.8"
alembic = "^1.6.5"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
flake8 = "^3.9.2"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
