name: CI
on:
    push:
        branches:
            - "**"
            - "!main"
        paths:
            - "**.py"
            - "poetry.lock"
    workflow_call: null
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - "3.9"
                    - "3.10"
                poetry-version:
                    - 1.1.15
        steps:
            - uses: actions/checkout@v3
            - name: "Set up Python ${{ matrix.python-version }}"
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"
            - uses: abatilo/actions-poetry@v2.2.0
              with:
                  poetry-version: "${{ matrix.poetry-version }}"
            - name: Install dependencies
              run: |
                  poetry install --no-root
            - name: Run flake8 and unittest
              run: |
                  poetry run flake8 --ignore E501 --statistics --show-source
                  poetry run python3 -m unittest
